### ISSUE TITLE
Field margin freaks out when changing margin

### ISSUE THREAD

**Issue by DanPeled** [BumbleB3339/BumbleBoard#1]
[Screencast from 2024-12-09 20-32-38.webm](https://github.com/user-attachments/assets/301a03ae-e9d3-4cd5-8421-149030e7cee4)
 (This isnt me modifying the margin, it does it by itself)

**Comment by DanPeled** [comment]
After further checks, this happens with all the widgets

**Comment by Amit02007** [comment]
Thank you for your feedback. This was an older version of the code that was mistakenly published alongside the release. The issue has been addressed in the release version :)
https://github.com/BumbleB3339/BumbleBoard/releases/tag/v1.0.0
