### ISSUE TITLE
SmartDashboard topics not being recognized anywhere

### ISSUE THREAD

**Issue by DanPeled** [BumbleB3339/BumbleBoard#4]
arent being found in the networktables add widget spot, arent being found either inside of additng the topic to a widget (e.g the field paths)

**Comment by Amit02007** [comment]
Thank you for your feedback. This was an older version of the code that was mistakenly published alongside the release. The issue has been addressed in the release version :)
https://github.com/BumbleB3339/BumbleBoard/releases/tag/v1.0.0
